runtime: php
env: flex

runtime_config: 
    document_root: public
    operating_system: "ubuntu22"
    runtime_version: "8.2"  

# Ensure we skip ".env", which is only for local development
skip_files: 
    - .env

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 1

resources:
    cpu: 2
    memory_gb: 4
    disk_size_gb: 100

env_variables:
    # Put production environment variables here.
    APP_DEBUG: true
    APP_ENV: production
    APP_KEY: base64:J8lkyjBJA6V3cI+s/ErSa7MJDMTBYaWx4NFXwPSxFZI=
    APP_NAME: "PayPro"

    LOG_LEVEL: debug

    DB_DATABASE: paypro
    DB_USERNAME: root
    DB_PASSWORD: klusterthon
    DB_SOCKET: '/cloudsql/optical-genre-405905:europe-west2:klusterthon273'

beta_settings:
    cloud_sql_instances: 'optical-genre-405905:europe-west2:klusterthon273'

build_env_variables:
  GOOGLE_COMPOSER_VERSION: 2.5.8