# steps:
#     name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#     entrypoint: 'bash'
#     args:
#         - '-c'
#         - |
#           gcloud config set app/cloud_build_timeout 3600 \
#           && gcloud app deploy -q --promote -v=$BUILD_ID \
#           --project=$PROJECT_ID

# timeout: '3600s'

steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 3600 && gcloud app deploy -q --promote -v=$BUILD_ID --project=$PROJECT_ID']

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: "bash"
  args:
    - "-c"
    - |
      RESPONSE=$(curl -o /dev/null -s -w "%{http_code}" -d "" -X POST $_APP_BASE_URL);
      if ["200" = $$RESPONSE]; then 
          echo "PASS migrations ran successfully"
          exit 1;
      else
          echo "FAIL migrations failed"
      fi

timeout: '3600s'